package auction_system.server.dao;

import auction_system.common.enums.UserRole;
import auction_system.server.model.User;

import java.math.BigDecimal;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class UserDAO {
    private static UserDAO instance;

    private UserDAO() {
    }

    public static UserDAO getInstance() {
        if (instance == null) {
            instance = new UserDAO();
        }
        return instance;
    }

    /*
        The save method is used to persist a User into the users table in MySQL.

        Current users table:
        id INT AUTO_INCREMENT PRIMARY KEY
        fullname
        username
        password
        roles
        balance

        No email anymore.
        No user_roles table anymore.
    */
    public void save(User user) {
        String sql = "INSERT INTO users(fullname, username, password, roles, balance) VALUES (?, ?, ?, ?, ?)";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            statement.setString(1, user.getFullname());
            statement.setString(2, user.getUsername());
            statement.setString(3, user.getPassword());
            statement.setString(4, rolesToString(user.getRoles()));
            statement.setBigDecimal(5, user.getBalance());

            statement.executeUpdate();

            // Retrieve the ID automatically generated by the database
            ResultSet keys = statement.getGeneratedKeys();
            if (keys.next()) {
                user.setId(keys.getInt(1)); // Assign back to the object
            }
        } catch (SQLException e) {
            throw new RuntimeException("Cannot save user", e);
        }
    }

    /*
        Convert Set<UserRole> to String to store in the roles column.

        Example:
        [BIDDER, SELLER] -> "BIDDER,SELLER"
    */
    private String rolesToString(Set<UserRole> roles) {
        StringBuilder result = new StringBuilder();

        for (UserRole role : roles) {
            if (!result.isEmpty()) {
                result.append(",");
            }

            result.append(role.name());
        }

        return result.toString();
    }

    /*
        Convert String in the database to Set<UserRole>.

        Example:
        "BIDDER,SELLER" -> Set containing BIDDER and SELLER
    */
    private Set<UserRole> stringToRoles(String rolesText) {
        Set<UserRole> roles = new HashSet<>();

        if (rolesText == null || rolesText.trim().isEmpty()) {
            return roles;
        }

        String[] parts = rolesText.split(",");

        for (String part : parts) {
            roles.add(UserRole.valueOf(part.trim()));
        }

        return roles;
    }

    /*
        The findByUsername method is used to find a user by username.

        Used for:
        - login
        - checking if username already exists
    */
    public User findByUsername(String username) {
        String sql = "SELECT * FROM users WHERE username = ?";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, username);

            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                return mapResultSetToUser(resultSet);
            }

            return null;

        } catch (SQLException e) {
            throw new RuntimeException("Cannot find user by username", e);
        }
    }
    
    /*
        The findById method is used to find a user by id.
    */
    public User findById(int id) {
        String sql = "SELECT * FROM users WHERE id = ?";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setInt(1, id);

            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                return mapResultSetToUser(resultSet);
            }

            return null;

        } catch (SQLException e) {
            throw new RuntimeException("Cannot find user by id", e);
        }
    }

    /*
        The update method is used to update user details in the database.

        No email anymore.
        roles resides directly in the users table.
    */
    public void update(User user) {
        String sql = "UPDATE users SET fullname = ?, username = ?, password = ?, roles = ?, balance = ? WHERE id = ?";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, user.getFullname());
            statement.setString(2, user.getUsername());
            statement.setString(3, user.getPassword());
            statement.setString(4, rolesToString(user.getRoles()));
            statement.setBigDecimal(5, user.getBalance());
            statement.setInt(6, user.getId());

            statement.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException("Cannot update user", e);
        }
    }

    /*
        The deleteById method is used to delete a user by id.

        No user_roles table anymore,
        so only need to delete from the users table.
    */
    public boolean deleteById(int id) {
        String sql = "DELETE FROM users WHERE id = ?";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setInt(1, id);

            int affectedRows = statement.executeUpdate();

            return affectedRows > 0;

        } catch (SQLException e) {
            throw new RuntimeException("Cannot delete user", e);
        }
    }

    /*
        The updateBalance method is used to update a user's balance.
    */
    public boolean updateBalance(int userId, BigDecimal newBalance) {
        String sql = "UPDATE users SET balance = ? WHERE id = ?";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setBigDecimal(1, newBalance);
            statement.setInt(2, userId);

            int affectedRows = statement.executeUpdate();

            return affectedRows > 0;

        } catch (SQLException e) {
            throw new RuntimeException("Cannot update balance", e);
        }
    }

    /*
        The mapResultSetToUser method is used to map database row data
        to a User Java object.

        Example database row:

        id    fullname        username    password    roles           balance
        1     Nguyen Van A    chuong      123456      BIDDER,SELLER   5000

        This method will create:
        new User("Nguyen Van A", "chuong", "123456", roles)
    */
    private User mapResultSetToUser(ResultSet resultSet) throws SQLException {
        int id = resultSet.getInt("id");
        String fullname = resultSet.getString("fullname");
        String username = resultSet.getString("username");
        String password = resultSet.getString("password");
        String rolesText = resultSet.getString("roles");
        BigDecimal balance = resultSet.getBigDecimal("balance");

        Set<UserRole> roles = stringToRoles(rolesText);

        if (roles.isEmpty()) {
            throw new RuntimeException("User has no role");
        }

        User user = new User(fullname, username, password, roles);

        user.setId(id);
        user.setBalance(balance);

        return user;
    }

    /*
        Retrieve all users in the users table.
    */
    public List<User> findAll() {
        String sql = "SELECT * FROM users";

        List<User> users = new ArrayList<>();

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                User user = mapResultSetToUser(resultSet);
                users.add(user);
            }

            return users;

        } catch (SQLException e) {
            throw new RuntimeException("Cannot find all users", e);
        }
    }
}